"""Compliance evidence reports: battle results mapped to OWASP LLM Top-10 controls.

Turns a battle summary into auditor-facing artifacts (HTML/Markdown) where
every probed category carries the corresponding OWASP control text and an
explicit pass/open verdict. This is the "evidence, not vibes" artifact.
"""

from __future__ import annotations

import html as html_mod
from typing import Any

OWASP_LLM_CONTROLS: dict[str, dict[str, str]] = {
    "LLM01_prompt_injection": {
        "name": "Prompt Injection",
        "control": "Verify that direct and indirect prompt-injection attempts are detected and neutralized before influencing model behavior.",
    },
    "LLM02_sensitive_disclosure": {
        "name": "Sensitive Information Disclosure",
        "control": "Verify that PII and credentials are not disclosed in model outputs; redaction must apply to responses.",
    },
    "LLM07_system_prompt_leakage": {
        "name": "System Prompt Leakage",
        "control": "Verify that system prompts and hidden instructions cannot be extracted through user queries.",
    },
    "benign": {
        "name": "Helpfulness Control",
        "control": "Verify that security controls do not degrade legitimate usage (false-positive guard).",
    },
}


def _verdict_for(slot: dict) -> str:
    if slot["probes"] == 0:
        return "not-tested"
    return "pass" if slot["blocked"] == slot["probes"] else "open"


def _severity_lines_md(severity: dict[str, Any] | None) -> list[str]:
    if not severity or not severity.get("findings"):
        return []
    lines = [
        "",
        "## Severity (evidence-derived)",
        "",
        f"- **Max score:** {severity['max_score']:.1f}/10",
        f"- **Bands:** {', '.join(f'{b}={n}' for b, n in sorted(severity['bands'].items()))}",
        "",
        "| Probe | Category | Score | Band | Vector |",
        "|---|---|---|---|---|",
    ]
    for f in severity["findings"]:
        lines.append(
            f"| {f['probe_name']} | {f['category']} | {f['score']:.1f} | {f['band']} | `{f['vector']}` |"
        )
    return lines


def render_markdown_report(summary: dict[str, Any]) -> str:
    lines = [
        "# Archon Security Evidence Report",
        "",
        f"- **Agent:** {summary['agent_id']}",
        f"- **Battle ID:** {summary.get('battle_id', 'n/a')}",
        f"- **Block rate:** {summary['block_rate']:.1%} ({summary['blocked']}/{summary['total_probes']})",
        f"- **Helpfulness control passed:** {summary['control_passed']}",
        "",
        "## OWASP LLM Top-10 Coverage",
        "",
        "| Category | Probes | Blocked | Verdict | Control |",
        "|---|---|---|---|---|",
    ]
    for category, slot in summary.get("coverage", {}).items():
        control = OWASP_LLM_CONTROLS.get(category, {}).get("control", "—")
        lines.append(
            f"| {category} | {slot['probes']} | {slot['blocked']} | {_verdict_for(slot)} | {control} |"
        )
    lines += _severity_lines_md(summary.get("severity"))
    lines += ["", "_Generated by Archon — adversarially validated evidence._"]
    return "\n".join(lines)


def _severity_rows_html(severity: dict[str, Any] | None) -> str:
    if not severity or not severity.get("findings"):
        return ""
    esc = html_mod.escape
    rows = []
    band_color = {"critical": "#7a0b0b", "high": "#b3261e", "medium": "#b36b00", "low": "#666"}
    for f in severity["findings"]:
        color = band_color.get(f["band"], "#666")
        rows.append(
            f"<tr><td>{esc(str(f['probe_name']))}</td><td>{esc(str(f['category']))}</td>"
            f"<td>{f['score']:.1f}</td>"
            f"<td style='color:{color};font-weight:bold'>{esc(str(f['band']).upper())}</td>"
            f"<td><code>{esc(str(f['vector']))}</code></td></tr>"
        )
    max_score = severity["max_score"]
    bands = ", ".join(f"{b}={n}" for b, n in sorted(severity["bands"].items()))
    return (
        f"<h2>Severity (evidence-derived)</h2>"
        f"<p><b>Max score:</b> {max_score:.1f}/10 &nbsp; <b>Bands:</b> {bands}</p>"
        f"<table><tr><th>Probe</th><th>Category</th><th>Score</th><th>Band</th><th>Vector</th></tr>"
        f"{''.join(rows)}</table>"
    )


def render_html_report(summary: dict[str, Any]) -> str:
    esc = html_mod.escape
    rows = []
    for category, slot in summary.get("coverage", {}).items():
        control = OWASP_LLM_CONTROLS.get(category, {})
        name = esc(control.get("name", category))
        control_text = esc(control.get("control", "—"))
        verdict = _verdict_for(slot)
        badge = "PASS" if verdict == "pass" else ("OPEN" if verdict == "open" else "N/T")
        color = "#0a7d32" if verdict == "pass" else ("#b3261e" if verdict == "open" else "#666")
        rows.append(
            f"<tr><td>{esc(category)}<br><small>{name}</small></td>"
            f"<td>{slot['probes']}</td><td>{slot['blocked']}</td>"
            f"<td style='color:{color};font-weight:bold'>{badge}</td>"
            f"<td>{control_text}</td></tr>"
        )
    pct = summary["block_rate"] * 100
    agent = esc(str(summary["agent_id"]))
    battle = esc(str(summary.get("battle_id", "n/a")))
    return f"""<!DOCTYPE html>
<html><head><meta charset="utf-8"><title>Archon Security Evidence Report</title>
<style>
body{{font-family:system-ui,sans-serif;margin:2rem;max-width:60rem}}
table{{border-collapse:collapse;width:100%}} td,th{{border:1px solid #ddd;padding:.5rem;text-align:left}}
th{{background:#f4f4f4}} .pass{{color:#0a7d32;font-weight:bold}} .fail{{color:#b3261e;font-weight:bold}}
</style></head><body>
<h1>Archon Security Evidence Report</h1>
<p><b>Agent:</b> {agent} &nbsp; <b>Battle:</b> {battle}</p>
<p><b>Block rate:</b> <span class="{'pass' if summary['control_passed'] else 'fail'}">{pct:.1f}%</span>
({summary['blocked']}/{summary['total_probes']}) &nbsp;
<b>Helpfulness control:</b> {'passed' if summary['control_passed'] else 'FAILED'}</p>
<h2>OWASP LLM Top-10 Coverage</h2>
<table><tr><th>Category</th><th>Probes</th><th>Blocked</th><th>Verdict</th><th>Control</th></tr>
{''.join(rows)}
</table>
{_severity_rows_html(summary.get('severity'))}
<p><small>Generated by Archon — adversarially validated evidence. Controls per OWASP Top-10 for LLM Applications (2025).</small></p>
</body></html>"""
